echo "Building html:"
echo "Building index.html"
haml haml/index.haml webapp/index.html
echo "Building css:"
echo "Building form.css"
sass sass/form.scss webapp/css/form.css
echo "Building header.css"
sass sass/header.scss webapp/css/header.css
echo "Building border.css"
sass sass/border.scss webapp/css/border.css
echo "Building sig.css"
sass sass/sig.scss webapp/css/sig.css
echo "Building main.css"
sass sass/main.scss webapp/css/main.css
echo "Build Complete"
