// Generated by CoffeeScript 1.6.1
var Upperlim, affalltext, affeditmode, affgrabtext, affpgcount, currpg, extendaff, lowerlim, maxchar, maxpgrenum, newaffpage, pnnum, pnrenum, pxtopt;

lowerlim = 9;

Upperlim = 12;

maxchar = 4600;

affpgcount = 1;

currpg = 1;

affalltext = "";

pxtopt = function(pixel) {
  return Math.round(pixel / ((.35146 / 25.4) * 96));
};

maxpgrenum = function() {
  $("[name='mpage']").each(function() {
    return $(this).val(affpgcount);
  });
};

pnrenum = function() {
  currpg = 1;
  $("[name='pn']").each(pnnum);
};

pnnum = function() {
  $(this).val(currpg);
  currpg = currpg + 1;
};

newaffpage = function(priorpage, ext) {
  var newpage, npchild;
  newpage = priorpage.clone(true);
  affpgcount++;
  npchild = newpage.find("[name='aff-f-1']");
  priorpage.after(newpage);
  npchild.val("");
  if (ext.length > maxchar) {
    npchild.val(ext.substring(0, maxchar));
    newaffpage(newpage, ext.substring(maxchar));
  } else {
    npchild.focus();
    maxpgrenum;
    pnrenum;
  }
};

affgrabtext = function(page) {
  var affta;
  console.log("grabtext");
  affta = page.find("[name='aff-f-1']");
  affalltext.concat(affta.val());
  if (page.find("[name='pn']").val() > 1) {
    page.remove();
  }
};

affeditmode = function() {
  affalltext = "";
  console.log("editmode");
  affpgcount = 1;
  $("[name='aff-1']").each(function() {
    return affgrabtext($(this));
  });
  maxpgrenum();
  console.log(affalltext);
  $("[name='aff-f-1']").val(affalltext);
};

extendaff = function(extra, priorpage) {
  var leftovers, newpage, npchild, temp;
  newpage = priorpage.clone(true);
  affpgcount++;
  newpage.attr("name", "aff-1");
  newpage.find("[name='pn']").val(affpgcount);
  temp = newpage.find("[name='paffi']");
  temp.attr('name', temp.attr('name'));
  temp = newpage.find("[name='affsig']");
  temp.attr('name', temp.attr('name'));
  temp = newpage.find("[name='date']");
  temp.attr('name', temp.attr('name'));
  temp = newpage.find("[name='affsig2']");
  temp.attr('name', temp.attr('name'));
  temp = newpage.find("[name='tcourt']");
  temp.attr('name', temp.attr('name'));
  npchild = newpage.find("[name='aff-f-1']");
  npchild.attr('name', "aff-f-1");
  leftovers = extra.substring(maxchar);
  npchild.val(extra.substring(0, maxchar));
  priorpage.after(newpage);
  maxpgrenum();
  if (leftovers.length > 0) {
    extendaff(leftovers, newpage);
  }
};

$(document).ready(function() {
  $(":input").focusout(function() {
    var ghost;
    if ($(this).attr('name') !== "aff-f-1") {
      ghost = $(":input[name=" + $(this).attr('name') + "]");
      ghost.val($(this).val());
      ghost.css('font-size', $(this).css('font-size'));
    }
  });
  $(":checkbox").click(function() {
    var ghost;
    ghost = $(":checkbox[name=" + $(this).attr('name') + "-g]");
    ghost.prop("checked", $(this).prop("checked"));
  });
  $(":checkbox[name^=cr]").click(function() {
    var c2, nametemp, temp;
    nametemp = $(this).attr('name');
    if (nametemp.indexOf("-c") >= 0) {
      $(this).prop("checked", true);
      nametemp = $(this).attr('name');
      nametemp = nametemp.substring(0, 3);
      $("[name=" + nametemp + "]").prop('checked', false);
    } else {
      temp = $(this).attr('name');
      c2 = $("[name=" + temp + "-c]");
      c2.prop("checked", false);
      $(this).prop("checked", true);
    }
  });
  $(":input").keydown(function() {
    var fontsize;
    if (this.scrollHeight > $(this).outerHeight() || this.scrollWidth > $(this).outerWidth()) {
      fontsize = parseInt($(this).css("font-size"), 10);
      fontsize = pxtopt(fontsize);
      if (fontsize > lowerlim) {
        $(this).css('font-size', (fontsize - 1) + "pt");
      }
    } else if (this.scrollHeight < $(this).outerHeight() || this.scrollWidth < $(this).outerWidth()) {
      fontsize = parseInt($(this).css("font-size"), 10);
      fontsize = pxtopt(fontsize);
      if (fontsize < Upperlim) {
        $(this).css('font-size', (fontsize + 1) + "pt");
      }
    }
  });
  $("[name='aff-f-1']").focusout(function() {
    var fs, ss, startingpage;
    fs = pxtopt(parseInt($(this).css('font-size')));
    while (this.scrollHeight > $(this).outerHeight() && fs > lowerlim) {
      $(this).css('font-size', fs + 'pt');
      fs--;
    }
    if ($(this).val().length > maxchar) {
      ss = $(this).val().substring(maxchar);
      $(this).val($(this).val().substring(0, maxchar));
      startingpage = $("[name='aff-1']");
      if (ss.length > 0) {
        extendaff(ss, startingpage);
      }
    }
  });
  $("[name='aff-f-1']").focusin(function() {
    affeditmode();
  });
  $(document).keydown(function() {
    if (event.which === 8 && !$(event.target).is("input, textarea")) {
      return e.preventDefault;
    }
  });
});
