// Generated by CoffeeScript 1.6.1
var lowerlim, pxtopt;

lowerlim = 8.5;

pxtopt = function(pixel) {
  return pixel / ((.35146 / 25.4) * 96);
};

$(document).ready(function() {
  $(":input").focusout(function() {
    var ghost;
    ghost = $(":input[name=" + $(this).attr('name') + "-g]");
    ghost.val($(this).val());
    return ghost.css('font-size', $(this).css('font-size'));
  });
  $(":checkbox").click(function() {
    var ghost;
    ghost = $(":checkbox[name=" + $(this).attr('name') + "-g]");
    return ghost.prop("checked", $(this).prop("checked"));
  });
  return $(":input").keydown(function() {
    var fontsize;
    if (this.scrollHeight > $(this).outerHeight()) {
      fontsize = parseInt($(this).css("font-size"), 10);
      fontsize = pxtopt(fontsize);
      if (fontsize > lowerlim) {
        return $(this).css('font-size', (fontsize - 1) + "pt");
      }
    }
  });
});
